### ISSUE TITLE
Migrate the support documentation to this repo

### ISSUE THREAD

**Issue by Andertech** [VividCortex/docs#1]
We need to migrate the support docs here. I suggest we do so step by step to enable open-source contribution afterwards. 

- [x] Make a Hugo implementation for the GH-Pages
- [x] Build Configuration
- [x] Move sections of plain html to the ´content´ folder and make sure the html structure is okay
- [x] Simplify site structure
- [x] Add the styles first, remove unused css from the website.
- [x] Add scripts
- [x] Create a nice README file
- [x] Review content and ...
- [x] Go live

ping @nachocaru h4x0r

**Comment by Andertech** [comment]
@nachocaru I could use some help removing the unnecessary CSS from the LESS files, and maybe if the remaining CSS is small just move everything to a single file.

**Comment by nachocaru** [comment]
Sure thing I can do that

**Comment by Andertech** [comment]
I think this is all done, I think the content is as fine as when we started the migration.
