### ISSUE TITLE
Document event types and their meanings

### ISSUE THREAD

**Issue by gkristic** [VividCortex/docs#102]
Some events have proven to be confusing for users, so we need to properly document what they mean. The idea is linking to this documentation directly from the app by event type.

**Comment by gkristic** [comment]
FYI @mtrias.

**Comment by mtrias** [comment]
:thumbsup:

**Comment by mtrias** [comment]
I'd add that it's desirable to have one anchor per event type, so that links can be easily constructed in the webapp

**Comment by potocnyj** [comment]
One thing that would be nice is if we could consolidate some of the event types under a single link - for instance we have events of the type `[Database Name] Connection Error`, that mean the same thing regardless of the technology we are using. Rather than copy/pasting the event type for each database technology we support, could we do something in the docs so they all go to a generic listing?

@nachocaru Any thoughts? Let me know if the above doesn't make sense ^

**Comment by gkristic** [comment]
Sounds reasonable to me.

**Comment by potocnyj** [comment]
I think I covered all of the ones that could really use an explanation, but there's a few that aren't listed such as agent start/stop events, configuration changes, etc. Do we want to add those as well?

**Comment by gkristic** [comment]
I think we do. Even if it's obvious what "agent stopped" or "agent started" mean, it's not necessarily obvious *why* they could stop/start without any action from the user. So it's a good place for note on that, telling users that this is also seen at the time agent updates are pushed. Configuration changes are also important IMO; what "configuration"?

**Comment by nachocaru** [comment]
Hey @potocnyj let me know whenever you have a couple of minutes free to talk about this  (yesterday you pinged me to talk, but I was very busy catching butterflies)

**Comment by potocnyj** [comment]
@nachocaru As discussed, here is a list of all of the database specific events we have and the corresponding generic event I've added documentation for:

Specific Event Type -> Generic Event Type
```
MySQL Server Stall -> Database Server Stall
PostgreSQL Server Stall -> Database Server Stall

MySQL Connection Error -> Database Connection Error
PostgreSQL Connection Error -> Database Connection Error
Redis Connection Error -> Database Connection Error
MongoDB Connection Error -> Database Connection Error

MySQL Configuration Change -> Database Configuration Change
PostgreSQL Configuration Change -> Database Configuration Change
Redis Configuration Change -> Database Configuration Change
MongoDB Configuration Change -> Database Configuration Change

MySQL Server Restart -> Database Server Restart
PostgreSQL Server Restart -> Database Server Restart
Redis Server Restart -> Database Server Restart
MongoDB Server Restart -> Database Server Restart
```

**Comment by potocnyj** [comment]
We decided to make a lot of the above events generic - the only ones in the list that are still unique to the database type are faults, as of Agents v1.7.122

**Comment by potocnyj** [comment]
@nachocaru we made the majority of agent events to be database agnostic, but ended up deciding that faults should stay the way they are for now. Can we add redirects for just the fault events?

**Comment by mtrias** [comment]
It seems to me that fault events are documented per host type ([MySQL server stall](http://docs.vividcortex.com/how-to-use-vividcortex/events-dashboard/#mysql-server-stall) for instance). Is that going to change?

**Comment by potocnyj** [comment]
That should really be named "Database Server Stall" in the documentation, it's written more as a general explanation rather than a database-specific one.

**Comment by mtrias** [comment]
Ok!

**Comment by gkristic** [comment]
This is ready. Closing.
