### ISSUE TITLE
Hosts filtering by tag

### ISSUE THREAD

**Issue by mtrias** [VividCortex/docs#113]
We say "Hosts can be tagged with name=value pairs" but there's no complete support for this. We should change this to just value tags.

**Comment by potocnyj** [comment]
Should we close https://github.com/VividCortex/docs/issues/33? It looks like this issue supersedes it.

**Comment by mtrias** [comment]
Yeah, though it looks like all the bottom portion of the page needs updates. Just created #114 too.
