### ISSUE TITLE
Description of notifications should include Failed Rules

### ISSUE THREAD

**Issue by mtrias** [VividCortex/docs#116]
This text from the Profiler documentation could be improved imo:

> Notifications (the bullhorn icon) is the number of warnings/notifications we’ve detected for this family of queries. Navigate to the query details for more information.

First, it uses the "notification" word as part of the explanation, so it's a bit of chicken-and-egg recursion. And second, it doesn't mention query errors nor failed rules (query advisor) notifications.

**Comment by Lowercases** [comment]
Related to this: the first image at https://docs.vividcortex.com/how-to-use-vividcortex/profiler/#viewing-query-notifications seems outdated -- the number of notifications doesn't show in the Profiler. Notice that it's followed by "Clicking on the notifications will show a drill-down into details." -- this can be confusing to the users.

**Comment by potocnyj** [comment]
Note that as of https://github.com/VividCortex/docs/pull/174 the language has been updated to specify notifications as errors and/or warnings. We should update it to further include failed rules once we've added relevant documentation for them (see #30)
