### ISSUE TITLE
Problem: Integrations page has dead links

### ISSUE THREAD

**Issue by AgentO3** [VividCortex/docs#125]
https://docs.vividcortex.com/how-to-use-vividcortex/integrations/

Solution: We should disable this page until alerts feature has a UI.

Note: The mockup for the integration page should display the instruction on how to obtain the credentials for a given 3rd integration inline with the configuration page. So we should probably not repeat those instructions in the documentations page.

**Comment by potocnyj** [comment]
I don't see any dead links in the documentation, so I'm going to close this as fixed.
