### ISSUE TITLE
Compare queries page opens with comparison to Top-queries page

### ISSUE THREAD

**Issue by fortxun** [VividCortex/docs#141]
The documentation for compare queries found [here](https://docs.vividcortex.com/how-to-use-vividcortex/compare-queries/) opens with the line "Compare Queries is very similar to Top Queries"

**Comment by nachocaru** [comment]
ping @mtrias this is solved [in this PR](https://github.com/VividCortex/docs/pull/144) let me know when to merge it.

**Comment by mtrias** [comment]
i'd say ship it now!

**Comment by nachocaru** [comment]
This was changed.
