### ISSUE TITLE
Invisible anchor link

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#156]
![image](https://cloud.githubusercontent.com/assets/379404/17302680/5755aad2-57eb-11e6-89ad-7a93a94de8ac.png)
http://docs.vividcortex.com/

**Comment by Preetam** [comment]
FYI @nachocaru

**Comment by nachocaru** [comment]
Fixed

**Comment by Preetam** [comment]
@nachocaru Can we go back to the previous behavior where those icons show up only when you hover over a header?

It doesn't look clean anymore.

![image](https://cloud.githubusercontent.com/assets/379404/17479671/cd0a3e2c-5d41-11e6-9c3e-a4fc83f23489.png)

Sorry my original issue text wasn't very clear. The main problem was that the icon didn't show up even after hovering over the header.

**Comment by nachocaru** [comment]
Nor proble man! sorry about that; I'll fix it right away
