### ISSUE TITLE
Query Samples and Privacy pages are not clear enough

### ISSUE THREAD

**Issue by potocnyj** [VividCortex/docs#163]
We got some recent feedback from a client that the documentation on Query Samples and how they can be configured to strip PII is not very clear. Specific things that need to be clarified:
- What is a sample really? e.g. what data does it contain, how is it useful?
- What options exist for sample capture?
- What are the trade-offs of these options? e.g. what do I get if I disable sending sample text vs. disabling sampling completely?

**Comment by seaparks** [comment]
I added additional information as part of https://github.com/VividCortex/docs/pull/237.
