### ISSUE TITLE
Clarify the two different role assignments and their effects

### ISSUE THREAD

**Issue by potocnyj** [VividCortex/docs#164]
The documentation [on roles](http://docs.vividcortex.com/general-reference/rbac/#roles) does a good job of describing the concepts of RBAC, but it is not very clear how access is affected when assigning a role to a team vs assigning a role to an environment-team coupling. We need to clarify the purpose of assigning a role to a team and how it affects permissions, so users better understand when to give a team a role and when to assign a role for a particular environment.

**Comment by laudares** [comment]
Waiting on [PR 284](https://github.com/VividCortex/docs/pull/284)

**Comment by laudares** [comment]
Branch merged with master through PR 284
