### ISSUE TITLE
[styling] Make block code styling consistent with inline

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#168]
Now:
http://docs.vividcortex.com/getting-started/installing/#for-mysql
![image](https://cloud.githubusercontent.com/assets/379404/18282849/da507c1c-7430-11e6-9a3c-6f6959eb5191.png)

Suggested:
![image](https://cloud.githubusercontent.com/assets/379404/18282876/f22aa772-7430-11e6-8bda-628a29f8c5dc.png)

FYI @nachocaru

**Comment by nachocaru** [comment]
👍

**Comment by nachocaru** [comment]
Made the changes, please reopen if I missed something.

**Comment by Preetam** [comment]
![image](https://cloud.githubusercontent.com/assets/379404/19250159/e7c0ab2e-8f06-11e6-9fb6-ba0c3fc9b25c.png)

I think it could use a little more padding, and the borders should be rounded.

**Comment by nachocaru** [comment]
Right, I added a bit more padding than the single line code and the round borders.
