### ISSUE TITLE
Broken links to PostgreSQL SUPERUSER privileges

### ISSUE THREAD

**Issue by cbandy** [VividCortex/docs#18]
There are three broken links to SQL files for creating stat functions that limit the superuser exposure needed for off-host monitoring.

[`getting-started/privileges.md`](http://docs.vividcortex.com/getting-started/privileges/#monitoring-without-superuser-privileges) links to `create-stat-functions-v92.sql`, `create-stat-functions-v90.sql`, and `create-stat-functions-v84.sql` which do not exist.

**Comment by mtrias** [comment]
@cbandy this markdown file is rendered into HTML to generate this page: https://www.vividcortex.com/docs/privileges/#monitoring-without-superuser-privileges

If you click on the rendered links, the download should work fine.

Reopen the issue otherwise.

**Comment by cbandy** [comment]
Indeed, the URL you've shown works perfectly. Somehow I ended up on http://docs.vividcortex.com, which does not behave well. I don't recall how I got there...

**Comment by mtrias** [comment]
Oh! in that case i'll reopen it because we actually need to fix it there!

Thanks for bringing this to our attention

**Comment by potocnyj** [comment]
I've published the latest version after merging a fix, @cbandy thanks again for letting us know about this!
