### ISSUE TITLE
Swifttype results include website

### ISSUE THREAD

**Issue by mtrias** [VividCortex/docs#19]
They should only include docs results IMO

![image](https://cloud.githubusercontent.com/assets/801752/10259970/1bbc1fbe-6945-11e5-9003-17bc02aff7e6.png)

**Comment by mtrias** [comment]
ping @Andertech

**Comment by Andertech** [comment]
I thought we should include both, since when you search in the website it will also show results to the docs. But I can change that in a minute anyway

**Comment by mtrias** [comment]
i think the problem is that the blog will have results for pretty much whatever keywords you input. So what when you really want to search on the docs?

IMO unless we could show like two separate categories of results for the same search (docs and blog), we should only show results in the docs site.

**Comment by nachocaru** [comment]
Swiftype is working on the docs now, and is showing results for the website and the docs.

**Comment by nachocaru** [comment]
Please re open if there are any issues with swiftype
