### ISSUE TITLE
Missing <hr> styling

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#191]
Maybe we can have something like
![image](https://cloud.githubusercontent.com/assets/379404/18641353/450e07fc-7e6a-11e6-9949-fa740c5198de.png)

@nachocaru

**Comment by nachocaru** [comment]
Hey @Preetam sorry for the daly in answering I'm still having issues with deploying new styles to netlify, but yeah it can be done.

**Comment by nachocaru** [comment]
Added the styling, please reopen if you want it to be smaller instead of 100% width
