### ISSUE TITLE
[Alerts] Feature is no longer in beta. Update Page

### ISSUE THREAD

**Issue by presstartgames** [VividCortex/docs#204]
![screen shot 2016-10-06 at 6 35 23 am](https://cloud.githubusercontent.com/assets/540305/19149280/13e04096-8b8f-11e6-8b99-929e1fa747ff.png)

**Comment by seaparks** [comment]
@presstartgames can we close this in light of: https://github.com/VividCortex/docs/pull/215

**Comment by presstartgames** [comment]
@seaparks Yep. Closing now.
