### ISSUE TITLE
Performance Schema Settings

### ISSUE THREAD

**Issue by presstartgames** [VividCortex/docs#206]
Need more information on settings.

Here is the instrumentation we use:
- **statements_digest** is used for capturing query metrics
- **events_statements_history_long** is used for capturing query samples

Both of the above are turned on/off via the **performance_schema.setup_consumers** table.

You can also enable all of the instrumentation matching **wait/synch/mutex/innodb/%** in the **setup_instruments** table, that will be used for populating the "Innodb_Mutexes" ranking in the Profiler.

**Comment by seaparks** [comment]
@presstartgames re: statements_digest and events_statements_history_long -- these are required for all off-host installs, right?

**Comment by presstartgames** [comment]
If you want to capture query metrics and query samples, yes.

**Comment by seaparks** [comment]
The first part of this has been addressed by https://github.com/VividCortex/docs/pull/249

The mutex instruments has another ticket Gus created, so I'm going to close this one.
