### ISSUE TITLE
"Loading" text after clicking on an image, clipped image

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#22]
Before:
![image](https://cloud.githubusercontent.com/assets/379404/10396502/d7a57272-6e70-11e5-8069-ff7a94e919bc.png)

After:
![image](https://cloud.githubusercontent.com/assets/379404/10396512/e178f67a-6e70-11e5-8792-0c2c5506855f.png)

The top of the image is clipped.

FYI @Andertech @nachocaru

**Comment by nachocaru** [comment]
Fixed.
