### ISSUE TITLE
no mention of cloud watch setup in the docs

### ISSUE THREAD

**Issue by fortxun** [VividCortex/docs#225]
I don't see any information about cloud watch integration in the docs

**Comment by seaparks** [comment]
note to myself: some documentation lives here: https://www.vividcortex.com/blog/cloudwatch-integration-in-vividcortex

**Comment by seaparks** [comment]
related to: https://github.com/VividCortex/docs/issues/122

**Comment by seaparks** [comment]
this has been added as part of https://github.com/VividCortex/docs/pull/249
