### ISSUE TITLE
Some images are blurry

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#227]
On this page: http://docs.vividcortex.com/general-reference/sso/

`max-width: 100%` makes some images blurry.

Now:

![image](https://cloud.githubusercontent.com/assets/379404/20714120/ec0de0c8-b618-11e6-9213-ef4b118950ba.png)

Without `max-width: 100%`:

![image](https://cloud.githubusercontent.com/assets/379404/20714096/db605986-b618-11e6-8200-95e9728cf545.png)

@nachocaru Feel free to close this as a "won't fix." I can't think of a good fix :).

**Comment by nachocaru** [comment]
A good fix is to take the screenshot again (using a smaller window in order to avoid css resizing it); I'll do it

**Comment by nachocaru** [comment]
Ok, I chnaged the image for a new one.
