### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by potocnyj** [VividCortex/docs#23]
I suspect there are many places in our documentation where links to other docs pages are broken, due to the change in the path in the migration. For example, the link on the `Privileges` page that redirects back to the `Installing` page resolves to `https://www.vividcortex.com/docs/installing/`, when it should be `https://www.vividcortex.com/getting-started/installing/`.

We'll need to sweep through the pages and correct all of these.

**Comment by Andertech** [comment]
I think we solved this yesterday right @potocnyj ? should we close it?

**Comment by potocnyj** [comment]
Yep, sorry forgot to close this after the updates :+1:
