### ISSUE TITLE
Heading capitalization is inconsistent

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#230]
![image](https://cloud.githubusercontent.com/assets/379404/21063396/6db5b512-be23-11e6-8b7c-83be84c5656b.png)

---

![image](https://cloud.githubusercontent.com/assets/379404/21063411/7f1581ac-be23-11e6-9207-dbb967f02c79.png)

---

![image](https://cloud.githubusercontent.com/assets/379404/21063905/0e446e2c-be26-11e6-92e7-cdc63ec4e60a.png)

**Comment by seaparks** [comment]
https://github.com/VividCortex/docs/pull/263
