### ISSUE TITLE
Add description of static IP use for install and api

### ISSUE THREAD

**Issue by fortxun** [VividCortex/docs#234]
The following can be used for sites which wish to use a static IP
static-app.vividcortex.com and static-download.vividcortex.com

This would mean they can fix the IP addresses in their firewall, but to use it they wil need the flags --api-uri and --cdn-uri

Can this be described in the docs?

**Comment by seaparks** [comment]
@fortxun - do you happen to know the IP of the S3 bucket?

**Comment by seaparks** [comment]
We'll document this in our internal wiki somewhere.

**Comment by seaparks** [comment]
https://github.com/VividCortex/artifacts/issues/454
