### ISSUE TITLE
/how-to-use-vividcortex/metrics does not load when using HTTPS

### ISSUE THREAD

**Issue by seaparks** [VividCortex/docs#235]
Very oddly, https://docs.vividcortex.com/how-to-use-vividcortex/metrics/ does not work, but http://docs.vividcortex.com/how-to-use-vividcortex/metrics/ does. That appears to be the only page in the docs site that does not allow https.

@mtrias - not sure if anyone gets auto-notified for this repo so I tagged you :-D

**Comment by mtrias** [comment]
@seaparks That URL works for me. What do you see ?
![image](https://cloud.githubusercontent.com/assets/801752/21542777/35b675c6-cd9f-11e6-92c1-8582ff2cfdb5.png)

**Comment by seaparks** [comment]
Well...it of course now works for me. I wish I had included some screenshots just so I don't look insane.  Sorry for the distraction D-:
