### ISSUE TITLE
add deleting hosts reclaim licenses immediately

### ISSUE THREAD

**Issue by seaparks** [VividCortex/docs#240]
question got asked in Intercom as to how long someone needs to wait after deleting a host for the license to be available. Right now it's immediate for deletes, ~two hours for shutdowns.

**Comment by potocnyj** [comment]
I believe we already specify this information, it's actually duplicated between https://docs.vividcortex.com/getting-started/managing-hosts/ and https://docs.vividcortex.com/getting-started/troubleshooting/#how-do-i-remove-hosts

**Comment by seaparks** [comment]
Ah okay, I see that now @potocnyj. Do you mind if I add a line to that effect under the Quota section? Or is that too duplicative.

**Comment by seaparks** [comment]
I'll leave this be.
