### ISSUE TITLE
Footer links broken

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#243]
This link...

![image](https://cloud.githubusercontent.com/assets/379404/22025580/11d3424a-dc9c-11e6-9978-1a173d84d749.png)

goes to https://www.vividcortex.com/monitoring/integrations, but that gets stuck on a redirect loop.

![image](https://cloud.githubusercontent.com/assets/379404/22025603/22dbab68-dc9c-11e6-9017-467077f76c26.png)

FYI @nachocaru.

**Comment by seaparks** [comment]
In addition, "For PostgreSQL" goes to a 404 and "Community" is broken like "Integrations"

**Comment by seaparks** [comment]
also, this widget:
![image](https://cloud.githubusercontent.com/assets/23585699/22027876/4262b600-dca3-11e6-9b24-550e4afbec9b.png)

goes to a 404

**Comment by seaparks** [comment]
https://github.com/VividCortex/docs/pull/267

The widget is still broken, I'll create a new issue for that.
