### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#252]
This link goes to a broken page.

![image](https://cloud.githubusercontent.com/assets/379404/22338150/a5186714-e3b4-11e6-9991-5241fd20aea6.png)

![image](https://cloud.githubusercontent.com/assets/379404/22338160/b0045106-e3b4-11e6-9505-56c869378855.png)

**Comment by Preetam** [comment]
![image](https://cloud.githubusercontent.com/assets/379404/22338213/ccf2b67c-e3b4-11e6-9979-855ca7610518.png)

"Integrations" and "What's New" are also broken.

**Comment by seaparks** [comment]
https://github.com/VividCortex/docs/pull/267
