### ISSUE TITLE
“Moving Agents to a New Host” section not clear

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#255]
According to a user, [this](https://docs.vividcortex.com/getting-started/managing-hosts/#moving-agents-to-a-new-host) section is not clear. I think it needs some work too.

FYI @seaparks.

**Comment by seaparks** [comment]
There's some rework that has to happen on the Hosts page to make it clearer how agents, hosts, and monitored hosts related to one another, and how to move agents between them (if necessary). I'll try to do all of that rewriting as part of this.

**Comment by seaparks** [comment]
https://github.com/VividCortex/docs/pull/258
