### ISSUE TITLE
Page order changing

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#26]
The order changes every time I run `grunt`.

![image](https://cloud.githubusercontent.com/assets/379404/10855108/2e27fa4c-7f16-11e5-9da4-543a1974d0ed.png)
---
![image](https://cloud.githubusercontent.com/assets/379404/10855110/33e558a8-7f16-11e5-9dbb-18e89a3f0632.png)
---
![image](https://cloud.githubusercontent.com/assets/379404/10855136/5ba31fc4-7f16-11e5-9872-ab99d8e31840.png)

Ping @Andertech.

BTW, is there any way we can specify one of those pages to be the content for the section link? Right now, it seems that the first page becomes the destination, but that's not always the same.

**Comment by Andertech** [comment]
I think this might have something to do with Hugo, I'll look into it. We can hardcode the page so that this doesn't happen.

**Comment by nachocaru** [comment]
This can be solved using the weight parameter in the yaml, I'll implement one and then if it doesn't seem correct we can fix the order.
