### ISSUE TITLE
Footer widget on docs site goes to 404

### ISSUE THREAD

**Issue by seaparks** [VividCortex/docs#268]
cc: @mtrias - Should we just kill this? It's not on the main site, it doesn't look like. If it is and I just can't find it, maybe I can fix the widget myself; just point me in the right direction. 

![image](https://cloud.githubusercontent.com/assets/23585699/22689381/cd8c8696-ecfe-11e6-8d40-394ffc7ab5ba.png)

**Comment by mtrias** [comment]
Yeah... we should. 

@nachocaru can you please ?

FYI @arslotnick

**Comment by nachocaru** [comment]
Sure, I'll remove it.

**Comment by nachocaru** [comment]
Maybe we should use the same footer as in the app and the website

**Comment by mtrias** [comment]
I'd love to. But we need @arslotnick to 👍🏿  / 👎🏻

**Comment by arslotnick** [comment]
Definitely 👍🏿 -- let's match the docs header and footer with those currently on the site.

**Comment by mtrias** [comment]
@arslotnick wait, which site are your referring to: www.vividcortex.com or https://www.vividcortex.com/free-trial-sign-up ?

**Comment by arslotnick** [comment]
Ah, sorry for not being clear. The footer is the same in both cases, so
let's match that.

Ideally, we'd be able to match the docs pages' header with the header on
www.vividcortex.com. But if that's too much at the moment, I think setting
it to match https://www.vividcortex.com/free-trial-sign-up is okay for now.
What do you think?

**Comment by mtrias** [comment]
We can do whatever is needed. 

Matching www.vividcortex.com has the disadvantage of being fragile, so until we can create automated tests to check that all the links are valid and we display the same content in both places, we could see it breaking or getting outdated again.

**Comment by arslotnick** [comment]
That makes sense. Let's stick with the https://www.vividcortex.
com/free-trial-sign-up header for now. Thanks!
