### ISSUE TITLE
Links inside a table are not easy to spot

### ISSUE THREAD

**Issue by potocnyj** [VividCortex/docs#269]
Example:
![image](https://cloud.githubusercontent.com/assets/2791006/22698821/a54b195c-ed23-11e6-95a4-8c8b56fbc80c.png)

There's two hyperlinks in that screenshot, but the text for them is grey until you hover over them:
![image](https://cloud.githubusercontent.com/assets/2791006/22698864/c7b4a120-ed23-11e6-93b9-2c4db9c9f3f9.png)

**Comment by seaparks** [comment]
I can't find any literature as to why Hugo is doing this. I can override the behavior by typing the links as HTML and not as Markdown and then adding `style="color: #02bad1"` to every link, which does get the links to appear, but that might be messy and we might prohibit inline styles.

I don't know who the resident internal expert might be on this. @presstartgames maybe we can chat about it?

**Comment by Preetam** [comment]
CSS issue.

![recording](https://cloud.githubusercontent.com/assets/379404/22745394/6ccce404-edee-11e6-95f0-dd15dd1cb655.gif)

**Comment by seaparks** [comment]
@nachocaru a little bird told me you're the CSS expert I should ping to get an opinion on how to fix that ^ :-D

**Comment by nachocaru** [comment]
@seaparks I'll fix it, don't worry.
