### ISSUE TITLE
clean_metrics doesn't under "Top Process"

### ISSUE THREAD

**Issue by laudares** [VividCortex/docs#276]
The second to last paragraph in https://docs.vividcortex.com/how-to-use-vividcortex/faults/ mentions:

> In the Top Processes widget below the summary, the culprit is visible: a process called clean_metrics.

except there's no process named **clean_metrics** listed under "Top Processes"

1) Was the screen shoot used there updated recently and the clean_metrics process has since been renamed ?

**Comment by seaparks** [comment]
Closed in https://github.com/VividCortex/docs/pull/278
