### ISSUE TITLE
Update host filter documentation for exact match

### ISSUE THREAD

**Issue by mtrias** [VividCortex/docs#28]
This page needs an update after we changed the feature in https://github.com/VividCortex/ng-app/pull/3212
https://docs.vividcortex.com/how-to-use-vividcortex/host-filter/

**Comment by Andertech** [comment]
What should the text be? Or should we just remove the ```$``` selector part?

**Comment by mtrias** [comment]
The text copy should not be changed. Is a minor just update to use quotes instead of `$`
