### ISSUE TITLE
Link to OneLogin Authentication is Incorrect.

### ISSUE THREAD

**Issue by presstartgames** [VividCortex/docs#289]
On https://docs.vividcortex.com/general-reference/sso/

the OneLogin anchor links to a localhost URL

![screen shot 2017-02-25 at 8 19 35 am](https://cloud.githubusercontent.com/assets/540305/23331398/39b50a7c-fb33-11e6-963a-ba5e14826183.png)

**Comment by seaparks** [comment]
https://github.com/VividCortex/docs/pull/290
