### ISSUE TITLE
Add Windows related documentation

### ISSUE THREAD

**Issue by gkristic** [VividCortex/docs#31]
We have to update the supported systems section and add any Windows-specific instructions.

**Comment by nachocaru** [comment]
@efepapa should we close this? or there are more specific pages that need to be created?

**Comment by gkristic** [comment]
More info is required. He's working on it.

**Comment by efepapa** [comment]
Oh.  I thought I was done with this.  What's missing?

**Comment by gkristic** [comment]
Oh, sorry... I didn't see you had already pushed and merged your changes. Ignore me.

**Comment by gkristic** [comment]
This is merged already. Closing.
