### ISSUE TITLE
Document how to set up PERFORMANCE_SCHEMA for remote monitoring

### ISSUE THREAD

**Issue by Andertech** [VividCortex/docs#36]
_From @Andertech on June 24, 2015 18:21_

_From @potocnyj on April 7, 2015 19:6_

Our docs should be all a customer needs to set up the app - let's document how to enable the PERFORMANCE_SCHEMA and the necessary consumers for RDS installation, so that we can point users to them if they have any trouble.

**Comment by Andertech** [comment]
Status on this @potocnyj ? Should I move this issue to the docs repo?

**Comment by Andertech** [comment]
_From @potocnyj on November 11, 2015 18:18_

Still needs to be done, we should move it.

**Comment by potocnyj** [comment]
This was done a while back but I forgot to close the issue, see http://docs.vividcortex.com/getting-started/installing/#installing-for-amazon-rds-for-mysql
