### ISSUE TITLE
Document the limitations for Free-BSD systems

### ISSUE THREAD

**Issue by Andertech** [VividCortex/docs#37]
We don't have feature parity for Free-BSD systems in terms of OS metrics that are captured - this needs to be documented, because we don't have anything that says this right now.

**Comment by Andertech** [comment]
should we move to docs ? ping @mtrias

**Comment by Andertech** [comment]
_From @potocnyj on November 11, 2015 18:19_

This may be outdated - for the most part I think we've reached feature Parity between linux and BSD. @Preetam anything major you know of that is missing?

**Comment by Andertech** [comment]
_From @Preetam on November 11, 2015 18:20_

I don't really remember. @efepapa?

**Comment by Andertech** [comment]
_From @efepapa on November 11, 2015 18:29_

A little grepping reveals...
```
func GetSocketStatus(samples chan telemetry.Sample, hostId uint64) {
        // TODO
}
```

```
func GetDisksUsage(samples chan telemetry.Sample, hostId uint64) {
        // TODO
}
```

```
func getFileDescriptorCount(pid uint32) (count uint32) {
        // Stub
        return uint32(0)
}
```

**Comment by Andertech** [comment]
I'm moving this to docs for consistency though.

**Comment by seaparks** [comment]
I'm going to close as the last comment believed there was parity. if it comes up again though I'm happy to document.
