### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by Preetam** [VividCortex/docs#41]
![image](https://cloud.githubusercontent.com/assets/379404/11184819/a7b5dfe4-8c47-11e5-80b1-02b845b2cf3b.png)

![image](https://cloud.githubusercontent.com/assets/379404/11184808/9eabc2d8-8c47-11e5-9578-f29b4e666a25.png)

FYI @Andertech @nachocaru

**Comment by Preetam** [comment]
Nevermind. It was something else :stuck_out_tongue:.

**Comment by nachocaru** [comment]
LOL
