### ISSUE TITLE
[Profiler]

### ISSUE THREAD

**Issue by mtrias** [VividCortex/docs#44]
We need to update the site after the Profiler is made public. Among others we should:

- [x] create the "/profiler" page using the content from top-queries
- [x] remove the top-queries and top-processes pages
- [x] redirect the top-queries and top-processes URLs to the new profiler documentation
- [ ] update the content with the changes in the tool

**Comment by mtrias** [comment]
@Andertech @nachocaru anyone wants to handle this?

**Comment by mtrias** [comment]
After doing this, please ship https://github.com/VividCortex/ng-app/pull/3393

**Comment by nachocaru** [comment]
Oh my, did not see this, sorry for the delay man! I'll check it out.

**Comment by mtrias** [comment]
No problem! i'm still working on other stuff before shipping so we are good!
