### ISSUE TITLE
Document how to move a host to a new env

### ISSUE THREAD

**Issue by xaprb** [VividCortex/docs#62]
From a customer:

> Is there some documentation/instruction on how to properly migrate a host to a different environment for VC?

Reply:

shut down the agents, edit /etc/vividcortex/global.conf and put the correct api token in there, then restart. You can find the right token by opening up the desired environment, opening the Add Host wizard and looking there. The metrics will remain, but in the old environment.

**Comment by potocnyj** [comment]
This exists at http://docs.vividcortex.com/getting-started/managing-hosts/#moving-a-host, but the title should be clearer.

**Comment by potocnyj** [comment]
Added a knowledge base article for this as well
