### ISSUE TITLE
Add documentation on RDS configuration

### ISSUE THREAD

**Issue by xaprb** [VividCortex/docs#64]
We have suprisingly little information on the setup process for RDS+MySQL. We don't say how to enable the statements digest setup consumer. We need something like this:

verify that the statements_digest consumer is enabled in the Performance Schema setup_consumers table. If not, you'll need to enable that. Then the agents will capture query performance metrics.

Check it:

     select * from performance_schema.setup_consumers where name = 'statements_digest';

That should say YES in the ENABLED column. If not:

     update performance_schema.setup_consumers set enabled='YES' where name = 'statements_digest';

**Comment by potocnyj** [comment]
As a follow up here, we had a support conversation this morning asking about the steps to configure a RDS host, and they specifically mentioned that the documentation could use some work here.

**Comment by potocnyj** [comment]
The install documentation could definitely still be improved, but I think #79 covered this specific issue well enough.
