### ISSUE TITLE
Update install/start/stop docs

### ISSUE THREAD

**Issue by xaprb** [VividCortex/docs#65]
Someone reported that /etc/init.d/vividcortex didn't exist after installation on ubuntu 12.04. https://vividcortex.com/docs/installing/ only mentions init.d and not systemctl or alternative init script dirs.

**Comment by potocnyj** [comment]
The docs no longer make any specific mention of init scripts as the install/uninstall script we provide handles that setup/teardown transparently. I'm going to go ahead and mark this as closed, please reopen if there's further action required here.
