### ISSUE TITLE
[Header] Dropdowns contain extra characters

### ISSUE THREAD

**Issue by presstartgames** [VividCortex/docs#72]
See the `|` in most rows.

![screen shot 2016-01-07 at 12 16 26 pm](https://cloud.githubusercontent.com/assets/540305/12177123/9c4af404-b538-11e5-9483-7be3e7012aa4.png)

![screen shot 2016-01-07 at 12 16 36 pm](https://cloud.githubusercontent.com/assets/540305/12177125/9ed17b6c-b538-11e5-944e-5b982f05811c.png)

**Comment by nachocaru** [comment]
Fixed.
