### ISSUE TITLE
Docs search not working

### ISSUE THREAD

**Issue by mtrias** [VividCortex/docs#96]
@nachocaru could you please take a look at this?

This is what i see:

![image](https://cloud.githubusercontent.com/assets/801752/12632389/50d1258a-c536-11e5-856e-9957b6484173.png)

**Comment by nachocaru** [comment]
Docs search is working now.

**Comment by mtrias** [comment]
Awesome! ... one thing i'd like to do is to focus the text box after pressing the loupe button. Is that possible ?

**Comment by nachocaru** [comment]
Nice catch I'll do it

**Comment by nachocaru** [comment]
Added focus

**Comment by mtrias** [comment]
#win
